name: Profile and detailed game history
uses: lowlighter/metrics@latest
with:
  filename: metrics-steam.full.svg
  token: NOT_NEEDED
  base: ""
  plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
  plugin_steam: yes
  plugin_steam_user: "0"
  plugin_steam_achievements_limit: 0
  plugin_steam_games_limit: 1
  plugin_steam_playtime_threshold: 2
  plugin_steam_recent_games_limit: 1
  plugin_steam_sections: player, most-played, recently-played
  plugin_steam_user: violetmail
